from enum import Enum 

class WeatherCode(Enum):
    CLEAR_SKY = 0
    MOSTLY_CLEAR = 1
    PARTLY_CLOUDY = 2
    OVERCAST = 3 
    FOG = 45
    RIME_FOG = 48
    DRIZZLE_LIGHT = 51 
    DRIZZLE_MODERATE = 53 
    DRIZZLE_HEAVY = 55 
    FREEZING_DRIZZLE_LIGHT = 56
    FREEZING_DRIZZLE_HEAVY = 57
    RAIN_LIGHT = 61
    RAIN_MODERATE = 63
    RAIN_HEAVY = 65
    FREEZING_RAIN_LIGHT = 66
    FREEZING_RAIN_HEAVY = 67
    SNOW_LIGHT = 71
    SNOW_MODERATE = 73 
    SNOW_HEAVY = 75
    SNOW_GRAINS = 77 
    RAIN_SHOWERS_LIGHT = 80
    RAIN_SHOWERS_MODERATE = 81
    RAIN_SHOWERS_HEAVY = 82
    SNOW_SHOWERS_LIGHT = 85
    SNOW_SHOWERS_HEAVY = 86
    THUNDERSTORM = 95
    THUNDERSTORM_HAIL_LIGHT = 96
    THUNDERSTORM_HAIL_HEAVY = 99